### PR TITLE
Make Blueprints/Snapshots copy building settings

### PR DESCRIPTION
**Pull request by daviscook477**
Allows for blueprints/snapshots to copy building settings that can be copied using the "copy" button in the UI for the building.

Copies the settings upon either instant building, or normal construction. Properly saves/loads the pending copied settings when buildings that are under construction are saved/loaded.

Introduces a setting (on by default) that enables/disables this copy functionality for blueprints.
Introduces a setting (on by default) that enables/disables this copy functionality for snapshots.

The reason for two separate settings is that the blueprint one has an impact on how large blueprints are saved to disk (whereas this is not a consideration for snapshots) and having many blueprints with copyable buildings loaded into memory at once will have a bigger memory impact (RAM).

The changes to the project files should probably not go through though (since they make building the project specific to my system and you probably want those files to work on your system for your workflow instead).

### CODE REVIEW

**Comment by EmoryStagmer** [comment]
I was about to start looking into this - do you have it working?

**Comment by daviscook477** [comment]
Yes this pull request is completely functional

**Comment by daviscook477** [comment]
@EmoryStagmer here is a link with a gif showing this pull request in action https://cdn.discordapp.com/attachments/541434730369777665/687389105398874206/blueprint_settings.gif

**Comment by jdfa** [comment]
@daviscook477 I completely support this feature, but looks like your changes are not completed. 
It works for liquid sensors (as described in gif), but i have an error for some automation items:
- NOT Gate
- AND Gate
- Signal Switch
- Ribbon Reader
- Ribbon Writer

Gif which shows the issue:
[https://imgur.com/0huwQtH](https://imgur.com/0huwQtH)

I haven't check ALL of the automation items, there might be an error in some other items as well. Also it works fine with some automations (Buffer Gate and Filter Gate).

**Comment by daviscook477** [comment]
@jdfa thanks for the heads up! This is why I wanted to leave it in testing so problems could be found. The gif makes sense. I'll reproduce it on my end and check the logs to resolve it.

I think I may decide to simply one by one go through and test each building to make sure all non-modded things end up working.

**Comment by daviscook477** [comment]
@jdfa it looks like in my testing I had checked both buildings with settings and without settings in normal construction mode but in instant build mode I only tested the buildings with settings.

My mistake was not confirming that a building had settings before trying to apply them in instant build mode. This recent commit should fix the issue.

**Comment by jdfa** [comment]
@daviscook477 Thanks for quick update! Now i dont see an error when blueprint contains that items.

But i still see some space for improvements. For some reason ribbon writers&readers as well as signal switch are not populating their properties on blueprints. Actually they have no Copy Settings button in UI, may be that's the reason. But i still think that this is pretty useful functionality. 
Can you check that?

**Comment by daviscook477** [comment]
Yeah I'll look into it. The way this code is written it will only work for buildings that have a "Copy Settings" button so that would at least explain why those ones can't have their properties copied. If there's a robust way to copy settings for them I'll try to add it, but this feature may end up being limited to just buildings with that "Copy Settings" button.

I totally see why not having the state of a signal switch or ribbon reader/writer could dampen the usefulness of this feature since it wouldn't be able to properly copy automation circuits.

**Comment by daviscook477** [comment]
@jdfa what would you think of the blueprint mod simply adding the "Copy Settings" button to the automation switch and ribbon reader/writer as part of fixing this issue.

The unfortunate situation is that since klei forgot to add in copy settings functionality for these buildings, there's no good way to have blueprints copy their settings. It might not be too bad of an idea for blueprints to simply implement the copy settings functionality for these 3 offending buildings and then it'll work.

Can you think of any other buildings that have settings you'd want to copy that don't have a "Copy Settings" button in game?

**Comment by daviscook477** [comment]
closed as too buggy. I don't think I can get it to work

**Pull request closed without merging**
